### ISSUE TITLE
Question - help me understand why use a local var in TThread.CreateAnonymousThread?

### ISSUE THREAD

**Issue by edwinyzh** [VSoftTechnologies/VSoft.CancellationToken#1]
Hello, Thank you again for another excellent Delphi library!
In the `procedure TCancellationTokenTests.TestCancel`, I see you use a local var `ltoken`  in `TThread.CreateAnonymousThread` to reference the variable in the outer procedure, as shown below:

```
procedure TCancellationTokenTests.TestCancel;
var
  token : ICancellationToken;
  cancelled : boolean;
begin
  FTokenSource.Reset;
  cancelled := false;
  token := FTokenSource.Token;
  TThread.CreateAnonymousThread(
    procedure
    var
      ltoken : ICancellationToken;
    begin
      lToken := token;
      while not lToken.IsCancelled do
```

I'm trying to understand the motivation, I guess it's for avoiding performance loss? 
Thanks!

**Comment by vincentparrett** [comment]
The cancellation tokens are reference counted objects, the ltoken local variable is ensuring the object is destroyed outside the thread.
