### ISSUE TITLE
[dcc32 Fatal Error] VSoft.HttpClient.pas(36): F2613 Unit 'VSoft.CancellationToken' not found.

### ISSUE THREAD

**Issue by beryindo** [VSoftTechnologies/VSoft.CancellationToken#2]
[dcc32 Fatal Error] VSoft.HttpClient.pas(36): F2613 Unit 'VSoft.CancellationToken' not found.

**Comment by vincentparrett** [comment]
VSoft.HttpClient has a dependency on VSoft.CancellationToken.

**Comment by beryindo** [comment]
where I can get VSoft.CancellationToken ? because I failed compile VSoft

**Comment by vincentparrett** [comment]
Umm. this is the VSoft.Cancellation token repository.. clone this repo, add the source folder to your project's search path.

**Comment by beryindo** [comment]
VSoft.HttpClient how to support http/2 ?
